/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteRouteImport } from './routes/_mainLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutLoginRouteRouteImport } from './routes/_mainLayout/login/route'
import { Route as MainLayoutEnrollTestPapersTwoRouteRouteImport } from './routes/_mainLayout/enroll-test-papers-two/route'
import { Route as MainLayoutEnrollTestPapersThreeRouteRouteImport } from './routes/_mainLayout/enroll-test-papers-three/route'
import { Route as MainLayoutEnrollTestPapersRouteRouteImport } from './routes/_mainLayout/enroll-test-papers/route'
import { Route as MainLayoutEnrollProblemTwoRouteRouteImport } from './routes/_mainLayout/enroll-problem-two/route'
import { Route as MainLayoutEnrollProblemThreeRouteRouteImport } from './routes/_mainLayout/enroll-problem-three/route'
import { Route as MainLayoutEnrollProblemRouteRouteImport } from './routes/_mainLayout/enroll-problem/route'
import { Route as MainLayoutAboutRouteRouteImport } from './routes/_mainLayout/about/route'
import { Route as MainLayoutProblemsIndexRouteImport } from './routes/_mainLayout/problems/index'
import { Route as MainLayoutProblemsProblemIdRouteImport } from './routes/_mainLayout/problems/$problemId'
import { Route as MainLayoutProblemsSchoolRouteRouteImport } from './routes/_mainLayout/problems/school/route'
import { Route as MainLayoutProblemsPopularRouteRouteImport } from './routes/_mainLayout/problems/popular/route'
import { Route as MainLayoutProblemsNewRouteRouteImport } from './routes/_mainLayout/problems/new/route'
import { Route as MainLayoutProblemsCourseRouteRouteImport } from './routes/_mainLayout/problems/course/route'

const MainLayoutRouteRoute = MainLayoutRouteRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutLoginRouteRoute = MainLayoutLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutEnrollTestPapersTwoRouteRoute =
  MainLayoutEnrollTestPapersTwoRouteRouteImport.update({
    id: '/enroll-test-papers-two',
    path: '/enroll-test-papers-two',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutEnrollTestPapersThreeRouteRoute =
  MainLayoutEnrollTestPapersThreeRouteRouteImport.update({
    id: '/enroll-test-papers-three',
    path: '/enroll-test-papers-three',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutEnrollTestPapersRouteRoute =
  MainLayoutEnrollTestPapersRouteRouteImport.update({
    id: '/enroll-test-papers',
    path: '/enroll-test-papers',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutEnrollProblemTwoRouteRoute =
  MainLayoutEnrollProblemTwoRouteRouteImport.update({
    id: '/enroll-problem-two',
    path: '/enroll-problem-two',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutEnrollProblemThreeRouteRoute =
  MainLayoutEnrollProblemThreeRouteRouteImport.update({
    id: '/enroll-problem-three',
    path: '/enroll-problem-three',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutEnrollProblemRouteRoute =
  MainLayoutEnrollProblemRouteRouteImport.update({
    id: '/enroll-problem',
    path: '/enroll-problem',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutAboutRouteRoute = MainLayoutAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutProblemsIndexRoute = MainLayoutProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutProblemsProblemIdRoute =
  MainLayoutProblemsProblemIdRouteImport.update({
    id: '/problems/$problemId',
    path: '/problems/$problemId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsSchoolRouteRoute =
  MainLayoutProblemsSchoolRouteRouteImport.update({
    id: '/problems/school',
    path: '/problems/school',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsPopularRouteRoute =
  MainLayoutProblemsPopularRouteRouteImport.update({
    id: '/problems/popular',
    path: '/problems/popular',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsNewRouteRoute =
  MainLayoutProblemsNewRouteRouteImport.update({
    id: '/problems/new',
    path: '/problems/new',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsCourseRouteRoute =
  MainLayoutProblemsCourseRouteRouteImport.update({
    id: '/problems/course',
    path: '/problems/course',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof MainLayoutAboutRouteRoute
  '/enroll-problem': typeof MainLayoutEnrollProblemRouteRoute
  '/enroll-problem-three': typeof MainLayoutEnrollProblemThreeRouteRoute
  '/enroll-problem-two': typeof MainLayoutEnrollProblemTwoRouteRoute
  '/enroll-test-papers': typeof MainLayoutEnrollTestPapersRouteRoute
  '/enroll-test-papers-three': typeof MainLayoutEnrollTestPapersThreeRouteRoute
  '/enroll-test-papers-two': typeof MainLayoutEnrollTestPapersTwoRouteRoute
  '/login': typeof MainLayoutLoginRouteRoute
  '/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/problems': typeof MainLayoutProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof MainLayoutAboutRouteRoute
  '/enroll-problem': typeof MainLayoutEnrollProblemRouteRoute
  '/enroll-problem-three': typeof MainLayoutEnrollProblemThreeRouteRoute
  '/enroll-problem-two': typeof MainLayoutEnrollProblemTwoRouteRoute
  '/enroll-test-papers': typeof MainLayoutEnrollTestPapersRouteRoute
  '/enroll-test-papers-three': typeof MainLayoutEnrollTestPapersThreeRouteRoute
  '/enroll-test-papers-two': typeof MainLayoutEnrollTestPapersTwoRouteRoute
  '/login': typeof MainLayoutLoginRouteRoute
  '/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/problems': typeof MainLayoutProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainLayout': typeof MainLayoutRouteRouteWithChildren
  '/_mainLayout/about': typeof MainLayoutAboutRouteRoute
  '/_mainLayout/enroll-problem': typeof MainLayoutEnrollProblemRouteRoute
  '/_mainLayout/enroll-problem-three': typeof MainLayoutEnrollProblemThreeRouteRoute
  '/_mainLayout/enroll-problem-two': typeof MainLayoutEnrollProblemTwoRouteRoute
  '/_mainLayout/enroll-test-papers': typeof MainLayoutEnrollTestPapersRouteRoute
  '/_mainLayout/enroll-test-papers-three': typeof MainLayoutEnrollTestPapersThreeRouteRoute
  '/_mainLayout/enroll-test-papers-two': typeof MainLayoutEnrollTestPapersTwoRouteRoute
  '/_mainLayout/login': typeof MainLayoutLoginRouteRoute
  '/_mainLayout/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/_mainLayout/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/_mainLayout/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/_mainLayout/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/_mainLayout/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/_mainLayout/problems/': typeof MainLayoutProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/enroll-problem'
    | '/enroll-problem-three'
    | '/enroll-problem-two'
    | '/enroll-test-papers'
    | '/enroll-test-papers-three'
    | '/enroll-test-papers-two'
    | '/login'
    | '/problems/course'
    | '/problems/new'
    | '/problems/popular'
    | '/problems/school'
    | '/problems/$problemId'
    | '/problems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/enroll-problem'
    | '/enroll-problem-three'
    | '/enroll-problem-two'
    | '/enroll-test-papers'
    | '/enroll-test-papers-three'
    | '/enroll-test-papers-two'
    | '/login'
    | '/problems/course'
    | '/problems/new'
    | '/problems/popular'
    | '/problems/school'
    | '/problems/$problemId'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/_mainLayout/about'
    | '/_mainLayout/enroll-problem'
    | '/_mainLayout/enroll-problem-three'
    | '/_mainLayout/enroll-problem-two'
    | '/_mainLayout/enroll-test-papers'
    | '/_mainLayout/enroll-test-papers-three'
    | '/_mainLayout/enroll-test-papers-two'
    | '/_mainLayout/login'
    | '/_mainLayout/problems/course'
    | '/_mainLayout/problems/new'
    | '/_mainLayout/problems/popular'
    | '/_mainLayout/problems/school'
    | '/_mainLayout/problems/$problemId'
    | '/_mainLayout/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainLayoutRouteRoute: typeof MainLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/login': {
      id: '/_mainLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLayoutLoginRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-test-papers-two': {
      id: '/_mainLayout/enroll-test-papers-two'
      path: '/enroll-test-papers-two'
      fullPath: '/enroll-test-papers-two'
      preLoaderRoute: typeof MainLayoutEnrollTestPapersTwoRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-test-papers-three': {
      id: '/_mainLayout/enroll-test-papers-three'
      path: '/enroll-test-papers-three'
      fullPath: '/enroll-test-papers-three'
      preLoaderRoute: typeof MainLayoutEnrollTestPapersThreeRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-test-papers': {
      id: '/_mainLayout/enroll-test-papers'
      path: '/enroll-test-papers'
      fullPath: '/enroll-test-papers'
      preLoaderRoute: typeof MainLayoutEnrollTestPapersRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-problem-two': {
      id: '/_mainLayout/enroll-problem-two'
      path: '/enroll-problem-two'
      fullPath: '/enroll-problem-two'
      preLoaderRoute: typeof MainLayoutEnrollProblemTwoRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-problem-three': {
      id: '/_mainLayout/enroll-problem-three'
      path: '/enroll-problem-three'
      fullPath: '/enroll-problem-three'
      preLoaderRoute: typeof MainLayoutEnrollProblemThreeRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/enroll-problem': {
      id: '/_mainLayout/enroll-problem'
      path: '/enroll-problem'
      fullPath: '/enroll-problem'
      preLoaderRoute: typeof MainLayoutEnrollProblemRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/about': {
      id: '/_mainLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutAboutRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/': {
      id: '/_mainLayout/problems/'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof MainLayoutProblemsIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/$problemId': {
      id: '/_mainLayout/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof MainLayoutProblemsProblemIdRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/school': {
      id: '/_mainLayout/problems/school'
      path: '/problems/school'
      fullPath: '/problems/school'
      preLoaderRoute: typeof MainLayoutProblemsSchoolRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/popular': {
      id: '/_mainLayout/problems/popular'
      path: '/problems/popular'
      fullPath: '/problems/popular'
      preLoaderRoute: typeof MainLayoutProblemsPopularRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/new': {
      id: '/_mainLayout/problems/new'
      path: '/problems/new'
      fullPath: '/problems/new'
      preLoaderRoute: typeof MainLayoutProblemsNewRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/course': {
      id: '/_mainLayout/problems/course'
      path: '/problems/course'
      fullPath: '/problems/course'
      preLoaderRoute: typeof MainLayoutProblemsCourseRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
  }
}

interface MainLayoutRouteRouteChildren {
  MainLayoutAboutRouteRoute: typeof MainLayoutAboutRouteRoute
  MainLayoutEnrollProblemRouteRoute: typeof MainLayoutEnrollProblemRouteRoute
  MainLayoutEnrollProblemThreeRouteRoute: typeof MainLayoutEnrollProblemThreeRouteRoute
  MainLayoutEnrollProblemTwoRouteRoute: typeof MainLayoutEnrollProblemTwoRouteRoute
  MainLayoutEnrollTestPapersRouteRoute: typeof MainLayoutEnrollTestPapersRouteRoute
  MainLayoutEnrollTestPapersThreeRouteRoute: typeof MainLayoutEnrollTestPapersThreeRouteRoute
  MainLayoutEnrollTestPapersTwoRouteRoute: typeof MainLayoutEnrollTestPapersTwoRouteRoute
  MainLayoutLoginRouteRoute: typeof MainLayoutLoginRouteRoute
  MainLayoutProblemsCourseRouteRoute: typeof MainLayoutProblemsCourseRouteRoute
  MainLayoutProblemsNewRouteRoute: typeof MainLayoutProblemsNewRouteRoute
  MainLayoutProblemsPopularRouteRoute: typeof MainLayoutProblemsPopularRouteRoute
  MainLayoutProblemsSchoolRouteRoute: typeof MainLayoutProblemsSchoolRouteRoute
  MainLayoutProblemsProblemIdRoute: typeof MainLayoutProblemsProblemIdRoute
  MainLayoutProblemsIndexRoute: typeof MainLayoutProblemsIndexRoute
}

const MainLayoutRouteRouteChildren: MainLayoutRouteRouteChildren = {
  MainLayoutAboutRouteRoute: MainLayoutAboutRouteRoute,
  MainLayoutEnrollProblemRouteRoute: MainLayoutEnrollProblemRouteRoute,
  MainLayoutEnrollProblemThreeRouteRoute:
    MainLayoutEnrollProblemThreeRouteRoute,
  MainLayoutEnrollProblemTwoRouteRoute: MainLayoutEnrollProblemTwoRouteRoute,
  MainLayoutEnrollTestPapersRouteRoute: MainLayoutEnrollTestPapersRouteRoute,
  MainLayoutEnrollTestPapersThreeRouteRoute:
    MainLayoutEnrollTestPapersThreeRouteRoute,
  MainLayoutEnrollTestPapersTwoRouteRoute:
    MainLayoutEnrollTestPapersTwoRouteRoute,
  MainLayoutLoginRouteRoute: MainLayoutLoginRouteRoute,
  MainLayoutProblemsCourseRouteRoute: MainLayoutProblemsCourseRouteRoute,
  MainLayoutProblemsNewRouteRoute: MainLayoutProblemsNewRouteRoute,
  MainLayoutProblemsPopularRouteRoute: MainLayoutProblemsPopularRouteRoute,
  MainLayoutProblemsSchoolRouteRoute: MainLayoutProblemsSchoolRouteRoute,
  MainLayoutProblemsProblemIdRoute: MainLayoutProblemsProblemIdRoute,
  MainLayoutProblemsIndexRoute: MainLayoutProblemsIndexRoute,
}

const MainLayoutRouteRouteWithChildren = MainLayoutRouteRoute._addFileChildren(
  MainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainLayoutRouteRoute: MainLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
